language: php

php: 
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --prefer-source --no-interaction --dev

script: phpunit -c phpunit.xml --coverage-text

after_script:
    - php vendor/bin/coveralls -v